### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by Riyue120** [codeartx/flash-switcher#10]
- Translation subtitle typesetting
翻译的文字不遵循统一的标准，有时在后面，有时在下面；还有出界的情况。
<img width="425" alt="msedge_gwonLW2swa" src="https://github.com/codeartx/flash-switcher/assets/84173649/71452fe7-e9fe-467c-bbc2-dfd2634389e3">

- Labeling problems
选择标注，第一次是背景变色，后面都是下划线的形式。
`alt+1`进行标注时，弹窗总是在鼠标边上，干扰使用，是否可以设置底部或置顶弹窗，选择颜色。
颜色有点出戏。
<img width="773" alt="msedge_X42jdzxtzW" src="https://github.com/codeartx/flash-switcher/assets/84173649/24408d7d-df38-4e70-bf62-89746758832e">
<img width="773" alt="msedge_967O7ymbHa" src="https://github.com/codeartx/flash-switcher/assets/84173649/28ea9f8b-1104-4722-9c30-22b54106990c">

- advice
标注能否进行多级标注，并大纲导出；每次打开浏览器，标注都会消失。

**Comment by codeartx** [comment]
谢谢你清晰的反馈，我会按照优先级陆续fix和更新的 🙏

**Comment by codeartx** [comment]
试试最新的 4.0 版本，笔记已经支持云同步了
![WechatIMG46](https://github.com/codeartx/flash-switcher/assets/54275314/4bcb3210-0a22-4cb2-a67f-134e24344653)
