### ISSUE TITLE
同一台电脑，不同浏览器，如edge和chrome，可以共享数据么？

### ISSUE THREAD

**Issue by hb-0** [codeartx/flash-switcher#11]
如题。

**Comment by codeartx** [comment]
> 如题。

当前不支持多端、跨浏览器云同步...书签可以使用浏览器自身的账号同步功能，笔记只能存在本地...

后续会推出云端同步功能，解决跨浏览器、跨设备的同步问题

**Comment by codeartx** [comment]
> 如题。

当前不支持多端、跨浏览器云同步...书签可以使用浏览器自身的账号同步功能，笔记只能存在本地...

后续会推出云端同步功能，解决跨浏览器、跨设备的同步问题
