### ISSUE TITLE
能否允许自主选择功能的开启

### ISSUE THREAD

**Issue by alan16742** [codeartx/flash-switcher#13]
扩展提供了很多的功能，个人只能使用一部分，没有使用的功能快捷键和其他扩展快捷键有冲突，如果调整快捷键过于繁琐以及可能带来冲突

**Comment by codeartx** [comment]
Good Idea👍...下个版本就加上该功能

**Comment by codeartx** [comment]
最新的 4.3.0 版已经支持了功能开关，默认只打开4大核心功能，其他更多功能可以根据自己需要开关，避免冲突

![截屏2024-03-30 14 23 03](https://github.com/codeartx/flash-switcher/assets/54275314/5c032136-7393-41ff-b10b-dc3f7120fbad)
<img width="1183" alt="截屏2024-03-30 14 34 07" src="https://github.com/codeartx/flash-switcher/assets/54275314/239652a7-07e9-4cb0-8669-369ecdf714fe">
