### ISSUE TITLE
outline-switch-overlay 覆盖原网页

### ISSUE THREAD

**Issue by kk140906** [codeartx/flash-switcher#14]
我发现这个隐藏的outline-switch-overlay即使没有调出页面也会存在, 这会影响原始网页的操作

![PixPin_2024-03-15_13-19-18](https://github.com/codeartx/flash-switcher/assets/23394525/ea0535e1-ac4d-4bd1-b798-b6ef37211114)

**Comment by codeartx** [comment]
好的，下个版本修复

**Comment by codeartx** [comment]
最新的4.3.0已修复这个问题，更新后试试看

![截屏2024-03-30 14 23 03](https://github.com/codeartx/flash-switcher/assets/54275314/8dd8c3f4-f2b3-4152-820f-eb5ddb138153)
