### ISSUE TITLE
请问如何切换中文？

### ISSUE THREAD

**Issue by surkaa** [codeartx/flash-switcher#15]
根据浏览器自动选择语言？为什么不能自己修改，我现在需要中文的，但是插件显示英文，并且找不到修改位置

**Comment by codeartx** [comment]
> 根据浏览器自动选择语言？为什么不能自己修改，我现在需要中文的，但是插件显示英文，并且找不到修改位置

根据浏览器语言自动设定的....尽量减少配置项让用户开箱即用....你浏览器语言是啥语言？

**Comment by surkaa** [comment]
安装的时候是Google账号是英文的（访问Gemini需要设置英文），浏览器是中文的，安装后插件显示是英文，然后谷歌账号切换中文后插件仍是英文的:
![image](https://github.com/codeartx/flash-switcher/assets/98200894/cf3d561a-7eb3-41b2-adfc-9d0fd94e47f0)
建议添加配置选项，选项默认可以根据浏览器语言自动设定，但是希望可以给用户提供自行调整的方式

**Comment by codeartx** [comment]
好的，会在近期版本中添加该配置，优先级：用户设置语言 > 自动探测浏览器语言

**Comment by codeartx** [comment]
我是根据用户浏览器的语言设置切换的，你可以试试看....还是不行的话，建议录个屏发我下，我试着重现，然后fix，尽量在最近的版本中解决这个问题

<img width="1474" alt="截屏2024-03-30 14 27 08" src="https://github.com/codeartx/flash-switcher/assets/54275314/983d48c4-7ce7-482d-864c-815b4798091a">

**Comment by surkaa** [comment]
我明白了 我之前是使用中文但是中文在语言列表中排第二，我将中文移到第一插件就显示中文了。感谢。
之前的图：
![image](https://github.com/codeartx/flash-switcher/assets/98200894/526e187c-0235-46f0-90d3-420ebe9eaca0)
