### ISSUE TITLE
Mac Chrome 翻译问题

### ISSUE THREAD

**Issue by QINLEITAN** [codeartx/flash-switcher#16]
翻译质量很差，不知到是用了哪个翻译器
而且没有重新翻译的选项
![image](https://github.com/codeartx/flash-switcher/assets/38026736/9d6be948-0c36-4b16-b1db-d33794273a3c)
能不能设置更换翻译工具，百度的翻译结果比较准确

**Comment by flash-kk** [comment]
后续版本会增加更多可选的引擎

**Comment by codeartx** [comment]
最新的 4.3.0 版本已经支持多引擎自主选择，可以试试看
![截屏2024-03-30 14 23 03](https://github.com/codeartx/flash-switcher/assets/54275314/2904d951-2d11-4a72-9172-7028a8c6a0e9)
<img width="1099" alt="截屏2024-03-30 14 25 48" src="https://github.com/codeartx/flash-switcher/assets/54275314/8ac3cec9-1615-413d-89e6-11c8945d7029">
