### ISSUE TITLE
ScienceDirect 网站无法翻译

### ISSUE THREAD

**Issue by mark0808008** [codeartx/flash-switcher#21]
![微信图片_20240415173207](https://github.com/codeartx/flash-switcher/assets/97501680/1c9a663f-1f35-4e51-979a-b174f3599ff

网站：https://www.sciencedirect.com/

之前偶尔有几次翻译成功过，但是现在基本都是只出现翻译中，一会儿进度消失后就没有了。

**Comment by mark0808008** [comment]
![image](https://github.com/codeartx/flash-switcher/assets/97501680/c436ba6c-1125-429f-9fe9-7ed390e3e889)

**Comment by codeartx** [comment]
好的，下个版本修复

**Comment by mark0808008** [comment]
好的，辛苦了，坐等，😄。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年4月15日 20:40
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [codeartx/flash-switcher] ScienceDirect 网站无法翻译 (Issue #21)
        
      
    
  

好的，下个版本修复

**Comment by mark0808008** [comment]
> 好的，下个版本修复

下个版本大概多久更新😄

**Comment by codeartx** [comment]
5.0 版本已修复这个问题

![截屏2024-05-23 20 47 06](https://github.com/codeartx/flash-switcher/assets/54275314/4bb67d80-1e8d-4b0f-ae89-3d4171ae44ea)

**Comment by mark0808008** [comment]
太棒了，啥时候上线？
