### ISSUE TITLE
最近标注内容

### ISSUE THREAD

**Issue by Xnhyacinth** [codeartx/flash-switcher#23]
你好，最近标注（alt+N）很多都不显示，但是搜索关键字可以出现最近标注内容，我的最近标注（alt+N）仅在更多栏目显示4.1及之前日期的部分内容，今天和本周栏目均为空，且最近日期标注内容也没有，（alt+x）同样的问题，请问这个是出了什么bug吗，我记得之前是好的，但改了这个栏目之后好像就不行了。
十分感谢！ @codeartx

**Comment by codeartx** [comment]
大小适配的，我的2块显示器都是正常显示，你的分辨率多少？

上面的2个问题会在下个版本里修复

**Comment by Xnhyacinth** [comment]
ok，十分感谢，分辨率是4k的显示器，之前好像是正常的，突然就这样了，并且只有（alt+x）

**Comment by Xnhyacinth** [comment]
> 大小适配的，我的2块显示器都是正常显示，你的分辨率多少？
> 
> 上面的2个问题会在下个版本里修复

下个版本还需要多久？

**Comment by Xnhyacinth** [comment]
> chrome 5.0 版本已更新，试试看

最近标注这个还是和之前一样，不搜索左边两栏为空，右边只显示了我最初3月份的标注内容，但搜索关键字后可以出现最近的标注内容。页面刷新了，同时我还重启了还是上面那两个问题。

**Comment by Xnhyacinth** [comment]
这是我自己的bug吗，大家都是正常的？
