### ISSUE TITLE
可否支持黑白名单

### ISSUE THREAD

**Issue by JianGuoHt** [codeartx/flash-switcher#24]
你好👋

### 起因：
身为一名开发人员再开发一些自己的站点时，当前插件会在控制台中打印一些日志信息或者错误提示；导致与开发时的一些错误混淆，影响开发效率；😣😣😣

### 建议：
是否可以针对不同的网址设置黑白名单（生效的站点）😀🥤🥤🥤😀。

**Comment by codeartx** [comment]
可以把打印的日志截图看下吗？我每次发布的时候尽量将所有日志都静默了，可能部分没注意到....
黑白名单机制是很好的安全机制，后续会支持的

**Comment by JianGuoHt** [comment]
![image](https://github.com/codeartx/flash-switcher/assets/48642259/b734e8a5-4ab1-45dd-8d78-61dfcd7646cc)

----------------

chrome-extension://k…agc/background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

**Comment by codeartx** [comment]
这个已经修复了，跟随下个版本这周上线

**Comment by codeartx** [comment]
浏览器插件可以选择作用范围的

![Uploading 截屏2024-07-24 16.58.32.png…]()
