### ISSUE TITLE
这插件与Brave浏览器的广告拦截器有冲突~

### ISSUE THREAD

**Issue by cutesniper22** [codeartx/flash-switcher#25]
测试环境：
-Windows 11 23H2
-Brave浏览器打开了内置的广告拦截器
-所有插件关闭，只打开flash copilot

在油管里，网页里有时候很多按钮按不到，要不就卡住好几秒恢复正常。
请看图~
![flash1](https://github.com/codeartx/flash-switcher/assets/26847827/810084ca-d1c1-4839-adb6-e39da2a42a49)

![flash2](https://github.com/codeartx/flash-switcher/assets/26847827/45bf4555-aba5-4d34-8b75-0263e172c301)

**Comment by codeartx** [comment]
当前仅支持 chrome 、edge 浏览器，并没有适配firefox等其他浏览器
