### ISSUE TITLE
关键字搜索和标注内容

### ISSUE THREAD

**Issue by Xnhyacinth** [codeartx/flash-switcher#27]
好像目前的搜索不支持模糊搜索，我必须输入完整的“inference”，而利用“infer”搜到的结果为空。

感觉这个可以优化一下。

然后就是可查看的标注内容太少并且我无法查看以前的标注内容只能依靠搜索，希望能上线支持查看所有标注内容，或者按时间查看标注内容。否则我标注了但我可能忘记了就不知道其内容，也无法通过搜索获取内容。

**Comment by codeartx** [comment]
好的，正在优化这块

**Comment by codeartx** [comment]
【5.2.0】版本已增强标注的检索，chrome上已通过，edge 在审核中

<img width="1758" alt="截屏2024-06-03 23 54 15" src="https://github.com/codeartx/flash-switcher/assets/54275314/eccde8d2-15ad-4cf0-b95a-2ed2747dc3fa">
