### ISSUE TITLE
存在大量重复请求问题

### ISSUE THREAD

**Issue by MianMianChan** [codeartx/flash-switcher#28]
类型：chrome浏览器插件
版本：5.2.0
一些网页存在大量的重复的加载js css 图片等静态资源以及内存缓存，导致页面卡死
贴两张请求的截图如下：
![image](https://github.com/codeartx/flash-switcher/assets/80753589/83f05d1f-6d37-4e4a-98be-26c52ea083e4)
![image](https://github.com/codeartx/flash-switcher/assets/80753589/a10d6061-be7a-4b71-b669-ea4984dda7a8)
![image](https://github.com/codeartx/flash-switcher/assets/80753589/2b66e09c-e91d-43e9-969f-6b6cea2f2917)

希望大佬解答一下😭卸载掉插件就一切正常了

**Comment by codeartx** [comment]
“一些网页存在” 可以把出现问题的链接发下吗？我未遇到这类网站，没有出现该问题，所以很难定位

**Comment by MianMianChan** [comment]
> “一些网页存在” 可以把出现问题的链接发下吗？我未遇到这类网站，没有出现该问题，所以很难定位
测试的几个网址如下：
截图1：https://devops.aliyun.com/projex/project  （云效：也是问题最严重，最经常使用的网站，主要体现在新建需求、任务页面）
截图2：https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html （spring的官网，用于测试）
截图3：https://juejin.cn/ （稀土掘金首页，同上）

**Comment by codeartx** [comment]
这是 Alt + W 快速预览和切换标签功能所致的，会及时监测页面变化并截图，因此会产生额外的请求和消耗资源...下个版本会优化这个问题，默认 Alt + W 关闭时不追踪和截图，以及增加其他优化策略

**Comment by codeartx** [comment]
【5.3.0】版本已经优化了该问题，chrome商店已通过审核，edge 至少要等1周
