### ISSUE TITLE
希望可以支持自定义设置快捷键

### ISSUE THREAD

**Issue by linzimu** [codeartx/flash-switcher#3]
发现chrome可以设置快捷键，但是360浏览器快捷键不知道怎么设置

**Comment by linzimu** [comment]
发现chrome能够设置快捷键，但是在360浏览器上设置不了，所以

**Comment by codeartx** [comment]
功能已开发完成，在下个大版本中一起上线

**Comment by codeartx** [comment]
> 发现chrome可以设置快捷键，但是360浏览器快捷键不知道怎么设置

已上线，可以试试最新版的特性
![Flash Copilot-封面](https://github.com/codeartx/flash-switcher/assets/54275314/0f8217f0-cbb0-45dd-ac77-4c23ed6e4c54)
