### ISSUE TITLE
侧边栏宽度

### ISSUE THREAD

**Issue by LiShiwei18** [codeartx/flash-switcher#31]
侧边栏可以调节宽度吗？现在好像不可以，有时候会挡住内容。
<img width="553" alt="image" src="https://github.com/codeartx/flash-switcher/assets/55582960/acd9420f-c1a3-46a6-af9d-efc0bdd23fd1">

**Comment by codeartx** [comment]
点击空白区域就自动隐藏了，不建议常驻
