### ISSUE TITLE
在Edge中，使用Edge版的插件在YouTube播放页出现性能问题，导致整个网站卡顿

### ISSUE THREAD

**Issue by qixing-jk** [codeartx/flash-switcher#32]
根据控制台信息分析应该原因为此
Refused to load the script 'https://www.youtube.com/s/player/5b22937f/player_ias.vflset/zh_CN/base.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Windows 11 Edge
Extension version 5.4.0

**Comment by codeartx** [comment]
看起来和我的插件无关，如果不触发视频转pdf功能，插件本身不会对视频播放页面做任何变动，理论上不会影响视频播放质量....

可能是这个播放脚本存在违法安全指令的问题，你可以卸载或禁用我的插件，刷新youtube的播放页面，是否还存在这个问题

**Comment by qixing-jk** [comment]
![Clip_20240628_211319](https://github.com/codeartx/flash-switcher/assets/125447674/40bf1907-a304-4269-b0a4-73193db5b9ea)
但事实上根据控制台的信息，脚本来源确实是此插件

**Comment by codeartx** [comment]
好的，我排查下

**Comment by codeartx** [comment]
暂时未遇到同类问题，实在不行可以远程下
