### ISSUE TITLE
页面右侧工具栏设置

### ISSUE THREAD

**Issue by ChuanzhengWei** [codeartx/flash-switcher#33]
非常感谢您设计的Flash Copilot，这是个好用的生产力工具！

我知道是否今天进行了后台更新（6.0.0），因为我将鼠标悬停在浏览器页面右侧时会出现一个工具栏，我想问是否有设置可以关闭/启用这个功能？在某些应用常用场景下，我不得不停用Flash Copilot来进行我的工作。
![微信截图_20240702100033](https://github.com/codeartx/flash-switcher/assets/137666181/f9df3db0-2ad2-459a-8a29-e6b5f74312ae)
![微信截图_20240702100107](https://github.com/codeartx/flash-switcher/assets/137666181/62eb341f-6f25-4bca-b9cc-023d47ee899d)

感谢！

**Comment by Tendo33** [comment]
有相同的问题，侧边栏有点影响正常工作。不得不暂时移除插件

**Comment by King98k** [comment]
同样遇到了这个问题，求问怎么关闭这个侧边栏

**Comment by ChuanzhengWei** [comment]
非常感谢您考虑并改进了这项功能！
