### ISSUE TITLE
浏览器卡顿问题

### ISSUE THREAD

**Issue by King98k** [codeartx/flash-switcher#35]
最近开启了插件之后会导致浏览器页面变得特别卡顿，占用内存增加。关掉后浏览器的速度明显变快了 。不清楚是否有其他人也遇到过？

**Comment by codeartx** [comment]
升级到最新版 如 6.2.0，关闭（默认）alt+w工作空间 、alt + left/right等需要预览标签的功能，这类功能需要后台截图，占用内存，用不到的话关掉就行

**Comment by King98k** [comment]
好的 感谢您的回复，今天确实开启了alt +w 的快捷键
