### ISSUE TITLE
最近标注的问题

### ISSUE THREAD

**Issue by williamxxl** [codeartx/flash-switcher#36]
无法自动换行，显示不全，而且无法更改列数，只能三列这样子看很麻烦，而且因为显示不全，想要删减标注也很麻烦，建议可以自定义列宽列数还有可以自动换行
![微信图片_20240722213757](https://github.com/user-attachments/assets/37040471-3af4-48ff-b179-d6dbcd0a89e0)

**Comment by codeartx** [comment]
这里只是为了检索和预览，并不是为了查看和编辑用的，查看和编辑可以跳转该文章详情页
