### ISSUE TITLE
全局关闭菜单不生效，显示的时候点击关闭没有反应

### ISSUE THREAD

**Issue by ChihGodlee** [codeartx/flash-switcher#39]
全局关闭菜单不生效，显示的时候点击关闭没有反应。
经常出现，目前是在 ARC 和 Chrome 都有这个问题。

**Comment by codeartx** [comment]
alt + S 显示当前页面的全局菜单；alt+, ，全局开关菜单

**Comment by ChihGodlee** [comment]
![CleanShot 2024-09-01 at 23 13 07](https://github.com/user-attachments/assets/93d5f6cc-5fc5-4ace-9c67-e7e7c8f919c6)
不行，页面上有两个弹出菜单 fl-menu-container，可以看看截图里面，alt+,只能控制其中一个
