### ISSUE TITLE
可以考虑给 outline 添加总的折叠框吗？

### ISSUE THREAD

**Issue by Xxs-7** [codeartx/flash-switcher#4]
outline 出现后毕竟占据了页面不少的面积，并且没有退出快捷键，可以考虑给 outline 加个总的折叠，保持outline 停靠（也可以考虑给 outline 加个 resize）；或者有能够关闭 outline 的快捷键。

**Comment by flash-kk** [comment]
> outline 出现后毕竟占据了页面不少的面积，并且没有退出快捷键，可以考虑给 outline 加个总的折叠，保持outline 停靠（也可以考虑给 outline 加个 resize）；或者有能够关闭 outline 的快捷键。

再次按 alt + o，就可以关闭了，比鼠标点击折叠更快

**Comment by codeartx** [comment]
> outline 出现后毕竟占据了页面不少的面积，并且没有退出快捷键，可以考虑给 outline 加个总的折叠，保持outline 停靠（也可以考虑给 outline 加个 resize）；或者有能够关闭 outline 的快捷键。

再次按 alt + o，即可隐藏，比鼠标点击折叠更快
