### ISSUE TITLE
因标签页整页画面捕获导致的性能问题

### ISSUE THREAD

**Issue by qixing-jk** [codeartx/flash-switcher#43]
https://github.com/codeartx/flash-switcher/issues/42
之前在长网页遇到了此类问题，之前没定位到是未开启相关功能

现定位到了问题所在位置
与后台的capture-tab tabImageUpdated逻辑相关，根据功能逻辑分析，应是生成Alt+W显示标签页时所调用的预览图，并且此预览图按10秒一次的频率进行更新，造成的性能问题的可能是大量请求图片资源或大量的DOM树处理操作

> **隐私警告⚠️（实际的图片内容还是很让人害怕的，万一上传了呢，希望用浏览器扩展的都注意隐私和安全问题，扩展的权限真的很大）**
![Clip_20241029_021004](https://github.com/user-attachments/assets/f58a2d57-1c02-49cc-9c69-3192586146ac)
[Chrome 商店说明](https://chromewebstore.google.com/detail/flash-copilot%EF%BC%88%E5%8E%9F-flash-swi/klokphhomfboclhpijjcgbpdjoccaagc?hl=zh-CN&authuser=0#:~:text=%E3%80%90%E5%AE%89%E5%85%A8%E6%89%BF%E8%AF%BA%F0%9F%9B%A1%E3%80%91%0A%E5%9B%A0%E4%BB%8E%E4%BA%8B%E5%AE%89%E5%85%A8%E8%A1%8C%E4%B8%9A%E7%9A%84%E5%8E%9F%E5%9B%A0%EF%BC%8C%E6%9C%AC%E6%8F%92%E4%BB%B6%E5%AF%B9%E5%AE%89%E5%85%A8%E9%97%AE%E9%A2%98%E9%9D%9E%E5%B8%B8%E9%87%8D%E8%A7%86%EF%BC%8C%E6%89%80%E4%BB%A5%E8%AF%A5%E6%8F%92%E4%BB%B6%E4%B8%8D%E4%BC%9A%E4%B8%BB%E5%8A%A8%E6%90%9C%E9%9B%86%E3%80%81%E4%B8%8A%E4%BC%A0%E3%80%81%E5%AD%98%E5%82%A8%E7%94%A8%E6%88%B7%E7%9A%84%E4%BB%BB%E4%BD%95%E9%9A%90%E7%A7%81%E6%95%B0%E6%8D%AE%EF%BC%8C%E6%89%80%E6%9C%89%E6%95%B0%E6%8D%AE%E5%9D%87%E6%9C%AC%E5%9C%B0%E5%8C%96%E3%80%81%E7%A7%81%E6%9C%89%E5%8C%96%E3%80%82%0A%E5%8D%B3%E4%BE%BF%E6%98%AF%E4%B9%A6%E7%AD%BE%E5%90%8C%E6%AD%A5%E5%8A%9F%E8%83%BD%EF%BC%8C%E7%94%A8%E6%88%B7%E8%87%AA%E8%BA%AB%E4%B9%9F%E5%8F%AF%E4%BB%A5%E9%80%89%E6%8B%A9%E6%98%AF%E5%90%A6%E4%BD%BF%E7%94%A8google%E8%B4%A6%E5%8F%B7%E8%87%AA%E8%BA%AB%E7%9A%84%E5%90%8C%E6%AD%A5%E8%AE%BE%E7%BD%AE%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6%E7%9A%84%E5%90%8C%E6%AD%A5%E5%8A%9F%E8%83%BD%E3%80%82%E6%B2%89%E6%B5%B8%E5%BC%8F%E6%A0%87%E6%B3%A8/%E7%AC%94%E8%AE%B0%E5%8F%AF%E4%BB%A5%E6%A0%B9%E6%8D%AE%E8%87%AA%E8%BA%AB%E6%83%85%E5%86%B5%E9%80%89%E6%8B%A9%E6%98%AF%E7%A6%BB%E7%BA%BF%E7%89%88%E8%BF%98%E6%98%AF%E4%BA%91%E7%89%88%EF%BC%8C%E4%BD%86%E4%B8%8D%E8%A6%81%E5%90%8C%E6%AD%A5%E6%95%8F%E6%84%9F%E6%95%B0%E6%8D%AE%EF%BC%88%E5%A6%82%E8%B4%A6%E5%8F%B7%E3%80%81%E5%AF%86%E7%A0%81%E7%AD%89%EF%BC%89%EF%BC%9B)
**但从一开始的 [是bug](https://github.com/codeartx/flash-switcher/issues/20#issuecomment-2051915256) 到后来的 [登录是用户体验计划的需要，将来根据用户习惯，逐步淘汰不常用的功能](https://github.com/codeartx/flash-switcher/issues/38#issuecomment-2287691498) 再到现在明确检测到内部是有统计信息上传的，确实统计了使用情况 ，但统计数据和强制登录真没有关联吧，不登录不能收集统计数据吗难道？
那么之后呢，这些截图是否之后真的会被上传呢，虽然现在我不知道上传了没有**
> 
> ![Clip_20241029_005810](https://github.com/user-attachments/assets/3a2f812b-c91e-46e1-8782-c91f95a36bfd)
> ![Clip_20241029_010744](https://github.com/user-attachments/assets/39755363-5d29-4df3-a32a-be74f347486b)

希望能够优化代码逻辑，避免过多的捕获和截图，不必要的内容如图片等内容不显示在预览中

**Comment by codeartx** [comment]
担心上传的话，可以亲自抓包试试，截图只为本地预览用的，如果关闭相应的功能（如alt + w），自然就不会有截图和与之的性能问题了....事实上，新版相关的功能默认是关闭的，可以按需手动开关
