### ISSUE TITLE
art+t提示Failed to attach to https://elevenvr.net/ - probably because of enterprise policies.但使用侧边栏的翻译可以

### ISSUE THREAD

**Issue by banafish** [codeartx/flash-switcher#44]
![image](https://github.com/user-attachments/assets/4e2874b6-329e-4592-a189-2bd0c03084a9)

**Comment by codeartx** [comment]
这是该插件的问题吧，不是我的插件问题，可能2个插件的快捷键冲突了，你可以自定义下翻译的快捷键
