### ISSUE TITLE
不同浏览器导入同一个插件包使用,本机记录也无法同步

### ISSUE THREAD

**Issue by wandianjian** [codeartx/flash-switcher#47]

**Comment by codeartx** [comment]
可以升级为云用户，保存到云端，跨浏览器可以同步 https://kjeek.com/vip/

**Comment by wandianjian** [comment]
可以知道保存在本地哪里嘛，我之前的一些记录不见了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 中午11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [codeartx/flash-switcher] 不同浏览器导入同一个插件包使用,本机记录也无法同步 (Issue #47)




 
可以升级为云用户，保存到云端，跨浏览器可以同步 https://kjeek.com/vip/
