### ISSUE TITLE
快捷键显示页面空白

### ISSUE THREAD

**Issue by gu1u** [codeartx/flash-switcher#48]
只显示分类栏，每个分类里面都是空白的，显示暂无数据

**Comment by codeartx** [comment]
是离线安装的，还是应用商店在线安装的？

**Comment by gu1u** [comment]
应用商店安装的，卸载过很多次，重新安装也不行

**Comment by codeartx** [comment]
奇怪，很少出现这种情况....chrome 还是 edge？ 换个浏览器试试呢？或者用这个离线安装方法试试呢 https://www.crxsoso.com/webstore/detail/klokphhomfboclhpijjcgbpdjoccaagc
