### ISSUE TITLE
更换电脑能进行数据迁移么？或者是多端登录数据同步？

### ISSUE THREAD

**Issue by liumh5** [codeartx/flash-switcher#6]

**Comment by flash-kk** [comment]
书签可以使用 google或是edge账号的同步功能，标注暂时不支持，后续版本会加
<img width="1134" alt="截屏2024-01-04 09 01 22" src="https://github.com/codeartx/flash-switcher/assets/41842427/8b363048-4977-4630-9e82-86f2f5687965">

**Comment by codeartx** [comment]
书签可以使用 google或是edge账号的同步功能，标注暂时不支持，后续版本会加

<img width="1134" alt="294062001-8b363048-4977-4630-9e82-86f2f5687965" src="https://github.com/codeartx/flash-switcher/assets/54275314/b6f83c88-5f61-4206-9eb2-2df9048fef2a">
