### ISSUE TITLE
重复生成 名叫 test 的 indexedDB

### ISSUE THREAD

**Issue by WenBin-Zhang** [codeartx/flash-switcher#7]
<img width="315" alt="image" src="https://github.com/codeartx/flash-switcher/assets/37074329/a9fea90b-6704-493d-b99f-bdfe597dd975">

**Comment by codeartx** [comment]
> <img alt="image" width="315" src="https://private-user-images.githubusercontent.com/37074329/295078397-a9fea90b-6704-493d-b99f-bdfe597dd975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDM4OTgsIm5iZiI6MTcwNDg0MzU5OCwicGF0aCI6Ii8zNzA3NDMyOS8yOTUwNzgzOTctYTlmZWE5MGItNjcwNC00OTNkLWI5OWYtYmRmZTU5N2RkOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIzMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZjQxM2FhOWY0ZTBmYzY4NjE3OTM5NjRiNDVlNDcxZTZiMTUwOTVhZmQyYzkxOTAxMGY3ZGI4MDdlNDdjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ws6NQ74Lh9jTE3DqLMIz1glLodOt61K3mgyrQtCYm3U">

后续版本会修复该问题，也可能优先上线云端同步功能，不再推荐用本地存储

**Comment by codeartx** [comment]
最新的 4.x 版本优先推荐云笔记功能，本地存储不再推荐
