### ISSUE TITLE
macos   谷歌浏览器    右键  双语沉浸式翻译没了 

### ISSUE THREAD

**Issue by YingchenWang007** [codeartx/flash-switcher#8]
Chrome 已是最新版本
版本 122.0.6226.2（正式版本）dev (arm64)

**Comment by flash-kk** [comment]
对，3.0.6 版本取消了，右键太麻烦、至少需要 2 步，违背【效率第一原则】....直接用 alt + t 快捷键吧，最快...
<img width="947" alt="截屏2024-01-10 07 33 14" src="https://github.com/codeartx/flash-switcher/assets/41842427/acd50409-dbea-40a8-bebd-30ae62d54a17">

**Comment by codeartx** [comment]
对，3.0.6 版本取消了，右键太麻烦、至少需要 2 步，违背【效率第一原则】....直接用 alt + t 快捷键吧，最快...

<img width="947" alt="截屏2024-01-10 07 33 14" src="https://github.com/codeartx/flash-switcher/assets/54275314/c76ed8a5-7e00-4a45-8998-cb5648cf7a31">
