### ISSUE TITLE
提点异常状态

### ISSUE THREAD

**Issue by badboync** [codeartx/flash-switcher#9]
背景:我经常在大篇幅的英文文档中 ，标注一些重点，并附加说明或翻译

1.  网页右侧的 “标注悬浮框经常消失” ，我不得不再调出来； 且悬浮框内的   “某条内容”  有时会增加多余的换行
2.  右侧悬浮框存在“注解条目”，但是网页中 没有 高亮显示
3.  当我选中>100个单词进行备注时，右侧的悬浮框查看功能让我真的痛苦， 如果双击悬浮框可以弹出一个框，提供我查看完整内容和编辑备注就太好拉

**Comment by codeartx** [comment]
都是很好的提议，后续版本会逐渐完善

**Comment by codeartx** [comment]
> 背景:我经常在大篇幅的英文文档中 ，标注一些重点，并附加说明或翻译
> 
>     1. 网页右侧的 “标注悬浮框经常消失” ，我不得不再调出来； 且悬浮框内的   “某条内容”  有时会增加多余的换行
> 
>     2. 右侧悬浮框存在“注解条目”，但是网页中 没有 高亮显示
> 
>     3. 当我选中>100个单词进行备注时，右侧的悬浮框查看功能让我真的痛苦， 如果双击悬浮框可以弹出一个框，提供我查看完整内容和编辑备注就太好拉

都是很好的提议，后续版本会逐渐完善 👍

**Comment by codeartx** [comment]
> 背景:我经常在大篇幅的英文文档中 ，标注一些重点，并附加说明或翻译
> 
>     1. 网页右侧的 “标注悬浮框经常消失” ，我不得不再调出来； 且悬浮框内的   “某条内容”  有时会增加多余的换行
> 
>     2. 右侧悬浮框存在“注解条目”，但是网页中 没有 高亮显示
> 
>     3. 当我选中>100个单词进行备注时，右侧的悬浮框查看功能让我真的痛苦， 如果双击悬浮框可以弹出一个框，提供我查看完整内容和编辑备注就太好拉

试试最新的 4.0 版本，笔记已经支持编辑和云同步了

![WechatIMG46](https://github.com/codeartx/flash-switcher/assets/54275314/8933c2a8-88bf-4bdf-88c3-070661bc7f64)
